# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86193a123ae5da2a1ef46f1f1fb1978b00012e2f4ebf1117469837d8587391415ccacfbd12c8166ae1df3e923716916ce6911a2c626221e35155a526a872f950

test:
  secret_key_base: eaa9a96e96033c5743cdb4885af05c6f3fb0f9896b52ea54f8b421b1b42de13cb68175b9adbd13adc9c1500cd5db0fe0932fd7fdede4219b82b6416282e612ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
